uscan/config/routes.rb
Rails.application.routes.draw do
  
  get 'search/search' , to: "search#search", as: "search"
  get 'welcome/index' , to: "welcome#index", as: "back"
  
  resources :welcome
  resources :searchs
  resources :forms
  
  root :to => 'welcome#index'
  
end

uscan/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

uscan/app/models/form.rb
#This is for the comments it makes sure something is in the fields

class Form < ApplicationRecord
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
    validates :message, presence: true, length: {minimum: 5}
end

uscan/app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

uscan/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
end

uscan/app/controllers/forms_controller.rb
#Form Controller has CRUD functionalities


class FormsController < ApplicationController
    
    def index
        @form = Form.all
    end
    
    def new
        @form = Form.new
    end
    
    def show
        @form = Form.find(params[:id])
    end
    
    def create
        @form = Form.new(form_params)
        if @form.save
            redirect_to @form
        else
            render 'new'
        end
    end
    
    def edit
        @form = Form.find(params[:id])
    end
   
  def update
      @form = Form.find(params[:id])
      if @form.update(form_params)
          redirect_to @form
      else
          render 'edit'
      end
  end
   
   def destroy
       @form = Form.find(params[:id])
       @form.destroy
       
       redirect_to forms_path
   end

private 
def form_params
    params.require(:form).permit(:first_name, :last_name, :email, :message)
end
end

uscan/app/controllers/search_controller.rb
class SearchController < ApplicationController
    def index
    end
end

uscan/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  
  def show
  end
  
end

uscan/app/helpers/application_helper.rb
module ApplicationHelper
end

uscan/app/helpers/forms_helper.rb
module FormsHelper
end

uscan/app/helpers/search_helper.rb
module SearchHelper
end

uscan/app/helpers/welcome_helper.rb
module WelcomeHelper
end

uscan/app/views/contact/index.html.erb
<h1>Contact Us</h1>
<body id = "welcome">
<div>
  <h6>First Name</h6>
  <div class="input-group">
    <input type="text" class="form-control" aria-describedby="basic-addon1">
  </div>
  <h6>Last Name</h6>
  <div class="input-group">
    <input type="text" class="form-control" aria-describedby="basic-addon1">
  </div>
  <h6>Email Address</h6>
  <div class="input-group">
    <input type="text" class="form-control" aria-describedby="basic-addon1">
  </div>
  <h6>Message</h6>
  <div class="input-group">
    <input type="text" class="form-control" aria-describedby="basic-addon1">
  </div>
</div>
</body>

uscan/app/views/forms/edit.html.erb
<html lang="en"> 
<head>
  <link href="uscan/app/assets/stylesheets/search.css" rel="stylesheet">
</head>
<body id="comment">
  <h1>Editing Comment</h1>
  <%= form_for :form, url: form_path(@form), method: :patch do |f| %>
  <% if @form.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@form.errors.count, "error") %> prohibited
        this form from being saved:
      </h2>
      <ul>
        <% @form.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </p>
  
  <p>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </p>
  
  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
 
  <p>
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </p>
  
  <div  id="comment-submit-btn"> 
  <p>
    <%= f.submit 'Submit', :class => 'btn btn-success'%>
  </p>
  </div>
  
<% end %>
 
<div  id="comment-back-btn"> 
<%= button_to "Back",{ :action => "index", :controller =>"forms"}, :class => "btn btn-success ", :method => :get %>
</div>

</body>
</html>

uscan/app/views/forms/index.html.erb
<html lang="en"> 
<head>
  <link href="uscan/app/assets/stylesheets/search.css" rel="stylesheet">
  </head>
      <header class="container" id="login_navbar">
      <nav class="navbar navbar-inverse bg-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <%= link_to "UScan", root_path, class: "navbar-brand" %>
          </div>

          <ul class="nav navbar-nav navbar-right">
            <% if signed_in? %>
              <li><%= link_to "Comment",{ :action => "index", :controller =>"forms"},  :method => :get %></li>
              <li><%= link_to "Search",{ :action => "search", :controller =>"search"},  :method => :get %></li>
              <li><%= link_to "Sign out", sign_out_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign In", sign_in_path %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>

<body id="comment">
<div>

<h1>Comment Page</h1>

<%= button_to "Add A Comment",{ :action => "new", :controller =>"forms"}, :class => "btn btn-success ", :method => :get %>
<br>
<br>
<table>
  <tr>
    <th>User</th>
    <th>Message</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
  <% @form.each do |form| %>
    <tr>
      <td><%= form.first_name %></td>
      <td><%= form.message %></td>
      <td><%= link_to 'Show ', form_path(form) %></td>
      <td><%= link_to ' Edit', edit_form_path(form) %></td>
      <td><%= link_to ' Destroy', 
                                form_path(form),
                                method: :delete,
                                data: { confirm: 'Are you sure?' }  %></td>
    </tr>
  <% end %>
</table>
</div>
</body>
</html>

uscan/app/views/forms/new.html.erb
<html>
<Head>
<link href="uscan/app/assets/stylesheets/search.css" rel="stylesheet">
</Head>
<body id="comment">
<h1>Leave us a comment</h1>

<%= form_for @form, url: forms_path do |f| %>
  
  <% if @form.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@form.errors.count, "error") %> prohibited
        this comment from being saved:
      </h2>
      <ul>
        <% @form.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </p>
    <p>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </p>
 
   <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
 
 
  <p>
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </p>
 <div  id="comment-submit-btn"> 
  <p>
    <%= f.submit 'Submit', :class => 'btn btn-success'%>
  </p>
  </div>
<% end %>

<div  id="comment-back-btn"> 
<%= button_to "Back",{ :action => "index", :controller =>"forms"}, :class => "btn btn-success ", :method => :get %>
</div>
</body>
</html>

uscan/app/views/forms/show.html.erb
<html lang="en"> 
<head>
    <link href="uscan/app/assets/stylesheets/search.css" rel="stylesheet">
    </head>
    <body id="comment">
        <fieldset>
        <div>
            <p>
                <strong>First Name</strong>
                <%= @form.first_name %>
                </p>
                
                <p>
                <strong>Last Name</strong>
                <%= @form.last_name %>
                </p>
                    
                <p>
                <strong>Email</strong>
                <%= @form.email %>
                </p>
                        
                <p>
                <strong>Message</strong>
                <%= @form.message %>
                </p>
                            
    <%= button_to "Back",{ :action => "index", :controller =>"forms"}, :class => "btn btn-success ", :method => :get %>
        </div>
        </fieldset>
    </body>
</html>

uscan/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>U-Scan</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

uscan/app/views/layouts/test.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>UScan</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    
  </head>

  <body>

    <header class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <%= link_to "U-Scan", root_path, class: "navbar-brand" %>
          </div>

          <ul class="nav navbar-nav navbar-right">
            <% if signed_in? %>
              <li><%= link_to "Comment",{ :action => "index", :controller =>"forms"},  :method => :get %></li>
              <li><%= link_to "Search",{ :action => "search", :controller =>"search"},  :method => :get %></li>
              <li><%= link_to "Sign out", sign_out_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign In", sign_in_path %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>

    <section class="container">
      <div id="flash">
        <% flash.each do |key, value| %>
          <div class="flash alert <%= alert_class(key) %>"><%= value %></div>
        <% end %>
      </div>
      <%= yield %>
    </section>
  </body>
</html>

uscan/app/views/search/contact.html.erb
<h1>You got nothing on me fam</h1>

uscan/app/views/search/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1">
    <meta name="description" content="">
    <meta name="Alex G, Billy The Kid, Jacob, Ryan, John" content="stuff">

    <title>Uscan</title>

    <!-- Bootstrap Core CSS -->
    <link href="uscan/app/assets/stylesheets/search.css" rel="stylesheet">


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link href="https://fonts.googleapis.com/css?family=Architects+Daughter|Roboto+Mono" rel="stylesheet">
</head>

<body>
    <!-- Testing Shit -->

  <!-- Done -->
    <div id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <li class="sidebar-brand">
                <div class="logo-bg"><a href="https://uscan-alxgnz.c9users.io/welcome/index">
                <img src="/assets/logo.png" style="max-width:200px; align: middle; display: block; margin: auto; padding: 5px;" ></a></div>
            </li>
            <li>
                <br>
                <img src="/assets/tuit.png">   Tuition <input class="form-check-input" type="checkbox"> 
                <br>$<span id="range1">1000</span>
                <br><input type="range" min="1000" max="100000" value="1000" step="100" onchange="showValue1(this.value)" class="slider" />
            </li>
            <li>
                <br>
                <img src="/assets/grad.png">   Gradution Rate <input class="form-check-input" type="checkbox"> 
                <br><span id="range2">0</span>%
                <br><input type="range" min="0" max="100" value="0" onchange="showValue2(this.value)" class="slider" />
            </li>
            <li>
                <br>
                <img src="/assets/accept.png">   Acceptence Rate <input class="form-check-input" type="checkbox"> 
                <br><span id="range3">0</span>%
                <br><input type="range" min="0" max="100" value="0"  onchange="showValue3(this.value)" class="slider" />
            </li>
            <li>
                <br>
                <img src="/assets/dist.png">   Distance <input class="form-check-input" type="checkbox"> 
            </li>
            <br><br>
            <li>
                <button onclick="store()" type="button" class="btn btn-success">Update Search</button>
            </li>
        </ul>
    </div>
    
               
                         <div id="googleMap" style="height: 100vh; position: relative; overflow: hidden; margin-left: 310px;"></div>
              

<script>
function myMap() {
var mapProp= {
    center:new google.maps.LatLng(38, -90),
    zoom:5,
};

var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);

var contentString = '<div id="content">'+
      '<div id="siteNotice">'+
      '</div>'+
      '<h1 id="firstHeading" class="firstHeading">University of North Carolina at Charlotte</h1>'+
      '<div id="bodyContent">'+
      '<p><b>Uluru</b>, also referred to as <b>Ayers Rock</b>, is a large ' +
      'sandstone rock formation in the southern part of the '+
      'Northern Territory, central Australia. It lies 335&#160;km (208&#160;mi) '+
      'south west of the nearest large town, Alice Springs; 450&#160;km '+
      '(280&#160;mi) by road. Kata Tjuta and Uluru are the two major '+
      'features of the Uluru - Kata Tjuta National Park. Uluru is '+
      'sacred to the Pitjantjatjara and Yankunytjatjara, the '+
      'Aboriginal people of the area. It has many springs, waterholes, '+
      'rock caves and ancient paintings. Uluru is listed as a World '+
      'Heritage Site.</p>'+
      '<p>Attribution: Uluru, <a href="https://en.wikipedia.org/w/index.php?title=Uluru&oldid=297882194">'+
      'https://en.wikipedia.org/w/index.php?title=Uluru</a> '+
      '(last visited June 22, 2009).</p>'+
      '</div>'+
      '</div>';

var infowindow = new google.maps.InfoWindow({
    content: contentString
  });

//this is how to add a marker 
var marker = new google.maps.Marker({
    position :new google.maps.LatLng(35.227085,-80.843124),
    url: 'http://www.uncc.edu/',
    map : map
})

marker.addListener('click', function() {
    infowindow.open(map, marker);
  });

google.maps.event.addListener(marker, 'click', function() {
      window.location.href = marker.url;
    });

    
}//end of function 



function showValue1(newValue)
{
	document.getElementById("range1").innerHTML=newValue;
}
function showValue2(newValue)
{
	document.getElementById("range2").innerHTML=newValue;
}
function showValue3(newValue)
{
	document.getElementById("range3").innerHTML=newValue;
}





</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDeYQKn0PrJNPBkpbGe7ihFbdOXSit4Oww&callback=myMap"></script>

</body>
</html>

<!-- https://api.data.gov/ed/collegescorecard/v1/schools?api_key=0PGR8AfEJpwx1vrAndIR6OT9elbqm5RH5dU6pg0g&_fields=id,school.name,school.city,school.state,school.zip,location.lat,location.lon&_per_page=100&_zip=28208&_distance=50mi&school.degrees_awarded.highest=3    -->

uscan/app/views/search/search.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1">
    <meta name="description" content="">
    <meta name="Alex G, Billy The Kid, Jacob, Ryan, John" content="stuff">

    <title>Uscan</title>

    <!-- Bootstrap Core CSS -->
    <link href="uscan/app/assets/stylesheets/search.css" rel="stylesheet">


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link href="https://fonts.googleapis.com/css?family=Architects+Daughter|Roboto+Mono" rel="stylesheet">
</head>

<body>

<!-- Side Bar -->
    <div id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <li class="sidebar-brand">
                <div class="logo-bg"><a href="https://uscan-alxgnz.c9users.io">
                    <img src="/assets/logo.png" style="max-width:200px; align: middle; display: block; margin: auto; padding: 5px;" ></a></div>
            </li>
            <li>
                <br>
                <img src="/assets/tuit.png">   Tuition <input class="form-check-input" type="checkbox" id='tuit_check'> 
                <br>$<span id="range1">1000</span>
                <br><input type="range" min="1000" max="100000" value="1000" step="100" onchange="showValue1(this.value)" class="slider" id="tuit_input" />
            </li>
            <li>
                <br>
                <img src="/assets/grad.png">   Gradution Rate <input class="form-check-input" type="checkbox" id="grad_check"> 
                <br><span id="range2">0</span>%
                <br><input type="range" min="0" max="100" value="0" onchange="showValue2(this.value)" class="slider" id="grad_input" />
            </li>
            <li>
                <br>
                <img src="/assets/accept.png">   Acceptence Rate <input class="form-check-input" type="checkbox" id="add_check"> 
                <br><span id="range3">0</span>%
                <br><input type="range" min="0" max="100" value="0"  onchange="showValue3(this.value)" class="slider" id="add_input"/>
            </li>
            <li>
                <br>
                <img src="/assets/dist.png">   Distance <input class="form-check-input" type="checkbox" id="dist_check"> 
                <br>
                <br>
                <div class="input-group" style='align: middle;'>
                     <span class="input-group-addon" id="sizing-addon2">ZipCode</span>
                      <input id='zip' type="text" class="form-control" placeholder="ex: 33016" aria-describedby="sizing-addon2" style='width: 80%'>
                    </div>
                <br>
                <div class="input-group" style='align: middle;'>
                     <span class="input-group-addon" id="sizing-addon2">Miles</span>
                      <input id='miles' type="text" class="form-control" placeholder="ex: 500" aria-describedby="sizing-addon2" style='width: 80%'>
                    </div>
            </li>
            <br><br>
            <li>
                <button onclick="myMap()" type="button" class="btn btn-success">Update Search</button>
            </li>
        </ul>
    </div>
<!-- End of Side Bar -->




<script>

function showValue1(newValue)
{
	document.getElementById("range1").innerHTML=newValue;
}
function showValue2(newValue)
{
	document.getElementById("range2").innerHTML=newValue;
}
function showValue3(newValue)
{
	document.getElementById("range3").innerHTML=newValue;
}
function Get(yourUrl){
    var Httpreq = new XMLHttpRequest(); // a new request
    Httpreq.open("GET",yourUrl,false);
    Httpreq.send(null);
    return Httpreq.responseText;          
}

</script>





<!-- Google Map  -->
<div id="googleMap" style="height: 100vh; position: relative; overflow: hidden; margin-left: 310px;"></div>
<!-- Google Map -->

<script>
function myMap() {
    
miles = document.getElementById('miles').value 
zip = document.getElementById('zip').value 
grad_val = (document.getElementById('grad_input').value)/100 
add_val = (document.getElementById('add_input').value)/100
tuit_val = document.getElementById('tuit_input').value 



url = 'https://api.data.gov/ed/collegescorecard/v1/schools.json?api_key=0PGR8AfEJpwx1vrAndIR6OT9elbqm5RH5dU6pg0g'+
'&school.degrees_awarded.highest=3'+
'&_fields=id,school.name,school.city,school.state,school.zip,location.lat,location.lon,2014.admissions.admission_rate.overall,'+
'2014.cost.tuition.in_state,2014.cost.tuition.out_of_state,2014.completion.completion_rate_4yr_150nt,school.school_url&_per_page=100'

distance = '&_zip='+zip+'&_distance='+miles+'mi'
tuit = '&2014.cost.tuition.in_state__range=..'+tuit_val
grad = '&2014.completion.completion_rate_4yr_150nt__range='+grad_val+'..'
accept = '&2014.admissions.admission_rate.overall__range='+add_val+'..'



if (document.getElementById('dist_check').checked) {
            url += distance
}
if (document.getElementById('add_check').checked) {
            url += accept
}
if (document.getElementById('grad_check').checked) {
            url += grad
}
if (document.getElementById('tuit_check').checked) {
            url += tuit
}



var json_obj = JSON.parse(Get(url));
console.log(json_obj);

    
    
    
var mapProp= {
    center:new google.maps.LatLng(36, -90),
    zoom:5,
    
};

var map = new google.maps.Map(document.getElementById("googleMap"),mapProp);



var contentString = [json_obj.results.length];
var infowindow = [json_obj.results.length];
var markers = [json_obj.results.length];
var count = 0;

while(count < json_obj.results.length){
    


 contentString[count] = '<h3>'+json_obj.results[count]["school.name"]+'</h3>'+
                    json_obj.results[count]["school.city"] +', '+json_obj.results[count]["school.state"]+
                    '<br><b>Acceptence Rate:</b> '+(json_obj.results[count]["2014.admissions.admission_rate.overall"]*100).toFixed(1)+'%'+
                    '<br><b>Graduation Rate:</b>'+(json_obj.results[count]["2014.completion.completion_rate_4yr_150nt"]*100).toFixed(1)+'%'+
                    '<br><b>In State Tuition:</b> '+json_obj.results[count]["2014.cost.tuition.in_state"]+
                    '<br><b>Out of State Tuition:</b> '+json_obj.results[count]["2014.cost.tuition.out_of_state"]+
                    '<br><a href="https://'+json_obj.results[count]["school.school_url"]+'">School Website</a>';

  infowindow[count] = new google.maps.InfoWindow({
    content: contentString[count]
  });

//this is how to add a marker 
  markers[count] = new google.maps.Marker({
    position :new google.maps.LatLng(json_obj.results[count]["location.lat"],json_obj.results[count]["location.lon"]),
    map : map,
});

var addListener = function (count) {
    google.maps.event.addListener(markers[count], 'click', function(){
        infowindow[count].open(map, markers[count]);                 
    });
}
addListener(count);


count += 1;



}//endloop   
    
    
}//end of function 


</script>





<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDeYQKn0PrJNPBkpbGe7ihFbdOXSit4Oww&callback=myMap"></script>

</body>

</html>

<!-- https://api.data.gov/ed/collegescorecard/v1/schools?api_key=0PGR8AfEJpwx1vrAndIR6OT9elbqm5RH5dU6pg0g&_fields=id,school.name,school.city,school.state,school.zip,location.lat,location.lon&_per_page=100&_zip=28208&_distance=50mi&school.degrees_awarded.highest=3    -->

uscan/app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

uscan/app/views/users/new.html.erb
<link href="uscan/app/assets/stylesheets/search.css" rel="stylesheet">
<body id="sign_in_page">
  <fieldset id="fieldset_box2">
    <div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>
  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>
    
    <div>
      <%= form.submit :class => "btn btn-success" %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>
</fieldset>
</body>

uscan/app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>UScan</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    
  </head>

  <body id="welcome">

    <header class="container">
      <nav class="navbar navbar-inverse bg-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <%= link_to "Uscan", root_path, class: "navbar-brand" %>
          </div>

               
          <ul class="nav navbar-nav navbar-right">
            <% if signed_in? %>
              <div class="navbar-brand navbar-center">
                Signed in as: <%= current_user.email %>
              </div>
              <li><%= link_to "Comment",{ :action => "index", :controller =>"forms"},  :method => :get %></li>
              <li><%= link_to "Search",{ :action => "search", :controller =>"search"},  :method => :get %></li>
              <li><%= link_to "Sign out", sign_out_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign In", sign_in_path %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>

    <section class="container">
      <div id="flash">
        <% flash.each do |key, value| %>
          <div class="flash alert <%= alert_class(key) %>"><%= value %></div>
        <% end %>
      </div>
      <%= yield %>
    </section>
    
    
<!--  <div class="vid-bg">
 <div class="vid-bg" style="background-color: #333; z-index: -10">
 
 </div>
 <video muted autoplay loop >
 
 <source src="/assets/landing.mp4" type="video/mp4">
 
 </video>
</div>
    -->
    
    <div id="home-logo">
     <img src="assets/home-logo.png" >
    </div>
  </body>
</html>

uscan/app/views/welcome/show.html.erb
<link href="uscan/app/assets/stylesheets/search.css" rel="stylesheet">
<body id="welcome">

<div  id="home-contact-btn">
    <%= button_to "Comment",{ :action => "index", :controller =>"forms"}, :class => "btn btn-success ", :method => :get %>
        
</div>
<div id="home-search-btn">
    <%= button_to "Search",{ :action => "search", :controller =>"search"}, :class => "btn btn-success ", :method => :get %>
</div>
</body>
 